### ISSUE TITLE
deploy on vercel fails

### ISSUE THREAD

**Issue by faierbol** [edgarlr/magazine#18]
Hi, congratz for this great template.
i have an issue while deploying to vercel, the deployment fails with:

`Build error occurred
10:55:45.159 | TypeError: articles.map is not a function
10:55:45.159 | at getStaticPaths (/vercel/path0/.next/server/pages/articles/[slug].js:5968:21)
10:55:45.159 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
10:55:45.160 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:16:80)
10:55:45.160 | at async /vercel/path0/node_modules/next/dist/build/utils.js:26:622
10:55:45.160 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:5:584)`

**Comment by faierbol** [comment]
Forgot to set the permissions on the api :/
